-- 코드를 입력하세요
SELECT u.USER_ID,u.NICKNAME,sum(price) as TOTAL_SALES
from USED_GOODS_BOARD b join USED_GOODS_USER u on b.WRITER_ID = u.USER_ID
where b.STATUS = 'DONE'
group by u.USER_ID
having sum(b.PRICE) >= 700000
order by TOTAL_SALES asc

# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
# WHERE B.STATUS = 'DONE'
# GROUP BY USER_ID 
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES ASC