-- 코드를 입력하세요
# CAR_RENTAL_COMPANY_CAR 테이블과 
# CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 
# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.

# 차 대여 일 수
# (SELECT (end_date-start_date + 1) as day
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY)

# select *
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY h join CAR_RENTAL_COMPANY_CAR c on h.CAR_ID = c.CAR_ID
# where CAR_TYPE = "트럭"

SELECT HISTORY_ID, ROUND(RENTAL_PERIOD * DISCOUNT_FEE,0) AS FEE
FROM (
SELECT HISTORY_ID, DAILY_FEE - (DAILY_FEE * (DC_RATE/100)) AS DISCOUNT_FEE, RENTAL_PERIOD
FROM (
SELECT HISTORY_ID, DAILY_FEE, RENTAL_PERIOD, 
    CASE WHEN PERIOD_TYPE = '90일 이상' 
    THEN (SELECT DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE CAR_TYPE = "트럭"
          AND DURATION_TYPE = "90일 이상")
    WHEN PERIOD_TYPE = '30일 이상' 
    THEN (SELECT DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE CAR_TYPE = "트럭"
          AND DURATION_TYPE = "30일 이상")
    WHEN PERIOD_TYPE = '7일 이상' 
    THEN (SELECT DISCOUNT_RATE
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
          WHERE CAR_TYPE = "트럭"
          AND DURATION_TYPE = "7일 이상")
    ELSE 0.00 END AS 'DC_RATE'
FROM (
SELECT HISTORY_ID, DAILY_FEE, RENTAL_PERIOD,
    CASE WHEN RENTAL_PERIOD >= 90 THEN '90일 이상'
         WHEN RENTAL_PERIOD >= 30 THEN '30일 이상'
         WHEN RENTAL_PERIOD >= 7 THEN '7일 이상'
    ELSE '7일 미만' END AS 'PERIOD_TYPE'
FROM(
SELECT A.CAR_ID, DAILY_FEE, HISTORY_ID, START_DATE, END_DATE, DATEDIFF(END_DATE,START_DATE)+1 AS 'RENTAL_PERIOD'
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
    ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "트럭"
    ) TBL_1 ) TBL_2 ) TBL_3 ) TBL_4
ORDER BY FEE DESC, HISTORY_ID DESC;